basicAuth:
  username: door3
  password: door3
assets:
  - quislex-db.sql.gz
steps:
  - name: Upgrade to php 7
    plugin: Script
    script: |
      echo 'exit 0' > /usr/sbin/policy-rc.d
      apt-get update
      apt-get install -y software-properties-common language-pack-en-base
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y php7.1 libapache2-mod-php7.1 php7.1-gd php7.1-curl php7.1-json php7.1-mbstring php7.1-mysql php7.1-mcrypt php7.1-imagick php7.1-dev php7.1-gmp php7.1-xml php7.1-bcmath php7.1-redis php7.1-uploadprogress
      cp /etc/php5/mods-available/general_settings.ini /etc/php/7.1/apache2/conf.d/20-general_settings.ini
      a2dismod php5
      a2enmod php7.1
      a2enmod mpm_prefork
      apache2ctl graceful
  - name: opcache
    plugin: Script
    script: |
      echo 'opcache.enable=1' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.enable_cli=1' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.memory_consumption=192' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.interned_strings_buffer=16' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.max_accelerated_files=3907' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.validate_timestamps=0' >> /etc/php/7.1/mods-available/opcache.ini
      echo 'opcache.fast_shutdown=1' >> /etc/php/7.1/mods-available/opcache.ini
      apache2ctl graceful
  - name: Update composer
    command: '/usr/local/bin/composer self-update'
  - name: Add Drupal package repository for Drupal 8.
    command: 'composer config -d /src/docroot/ repositories.drupal composer https://packages.drupal.org/8'
  - name: Install composer packages with dependencies.
    command: 'composer install -d /src/docroot/'
  - name: Quislex site provision
    drupalVersion: 8
    plugin: Drupal
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: false
    database: quislex-db.sql.gz
    databaseName: drupal
    databaseUser: drupal
    subDirectory: docroot
    settingsAppend: |
      $config_directories = ['sync' => '../config/sync'];
  - name: Post deploy commands
    plugin: Script
    script: |
      drush cim -y
      drush en -y stage_file_proxy
      drush -y config-set stage_file_proxy.settings origin 'http://quislex.door3dev.com/'
      drush -y config-set system.image toolkit 'gd'
      drush -y config-set system.file path.temporary '/tmp'
      drush cr
  - name: Uninstall Node
    plugin: Shell
    command: 'apt-get remove -y nodejs'
  - name: Add nodesource debs
    plugin: Shell
    command: 'wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - ; echo "deb https://deb.nodesource.com/node_8.x trusty main" > /etc/apt/sources.list.d/nodesource.list ; echo "deb-src https://deb.nodesource.com/node_8.x trusty main" >> /etc/apt/sources.list.d/nodesource.list'
  - name: Install nodejs
    plugin: Shell
    command: 'apt-get update; apt-get install --fix-missing -y nodejs'
  - name: Install gulp-cli
    plugin: Shell
    command: 'npm install -g gulp; npm install -g gulp-cli'
  - name: Install bower
    plugin: Shell
    command: 'npm install -g bower'
  - name: Pull down node modules
    plugin: Shell
    command: 'cd $SRC_DIR/docroot/themes/custom/quislex; npm install;'
  - name: Install bower dependecies
    plugin: Shell
    command: 'cd $SRC_DIR/docroot/themes/custom/quislex; bower --verbose --allow-root install;'
  - name: Compile frontend assets
    plugin: Shell
    command: 'cd $SRC_DIR/docroot/themes/custom/quislex; gulp build;'
