image: derh4nnes/pipeline-behat:feature_php-7.2
clone:
  depth: full
options:
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Unit/functional tests and static code analysis
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/code_tests.sh
      - step:
          name: Content features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh content db-dump
          services:
            - mysql
            - testing
      - step:
          name: Entities features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh entities db-dump
          services:
            - mysql
            - testing
      - step:
          name: Access features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh access db-dump
          services:
            - mysql
            - testing
      - step:
          name: View mode features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh view_mode db-dump
          services:
            - mysql
            - testing
      - step:
          name: Form features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh form db-dump
          services:
            - mysql
            - testing
      - step:
          name: Simplenews feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh simplenews db-dump
          services:
            - mysql
            - testing
      - step:
          name: Social media sharing feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh social_media_sharing db-dump
          services:
            - mysql
            - testing
      - step:
          name: Webforms feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh webforms db-dump
          services:
            - mysql
            - testing
      - step:
          name: Smoke tests
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh smoke_tests db-dump
          services:
            - mysql
            - testing
  branches:
    release/*:
      - parallel:
        - step:
            name: Unit/functional tests and static code analysis
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/code_tests.sh
        - step:
            name: Content features
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh content new-install
            services:
              - mysql
              - testing
        - step:
            name: Entities features
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh entities new-install
            services:
              - mysql
              - testing
        - step:
            name: Access features
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh access new-install
            services:
              - mysql
              - testing
        - step:
            name: View mode features
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh view_mode new-install
            services:
              - mysql
              - testing
        - step:
            name: Form features
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh form new-install
            services:
              - mysql
              - testing
        - step:
            name: Simplenews feature
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh simplenews new-install
            services:
              - mysql
              - testing
        - step:
            name: Social media sharing feature
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh social_media_sharing new-install
            services:
              - mysql
              - testing
        - step:
            name: Webforms feature
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh webforms new-install
            services:
              - mysql
              - testing
        - step:
            name: Smoke tests
            caches:
              - composer
            script:
              - sh $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh smoke_tests new-install
            services:
              - mysql
              - testing

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
    mysql:
      image: mysql:5.7
      memory: 1024
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: new_install