# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: derh4nnes/pipeline-behat:latest
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - composer create-project degov/degov-project
          - cd degov-project
          - composer require degov/degov:dev-$BITBUCKET_BRANCH#$BITBUCKET_COMMIT
          - php -S localhost:80 -t docroot &
          - export PATH="$HOME/.composer/vendor/bin:$PATH"
          - phpstan analyse docroot/profiles/contrib/degov -c docroot/profiles/contrib/degov/phpstan.neon --level=1 || true
          - (cd docroot/profiles/contrib/degov && phpunit)
          - bin/drush si degov --db-url=sqlite://sites/default/files/db.sqlite -y
          - mv docroot/profiles/contrib/degov/behat.yml .
          - behat
        services:
          - testing
    - step:
        name: Deploy to platform.sh
        script:
          - git config --global push.default matching
          - git remote add platform e5wm7rpj4nlbs@git.eu.platform.sh:e5wm7rpj4nlbs.git
          - git push platform $BITBUCKET_BRANCH
    - step:
        name: Push to drupal.org
        script:
          - git remote add drupal DerH4NNES@git.drupal.org:project/degov.git
          - git config --global push.default matching
          - git config --global user.name "SaschaHannes"
          - git push drupal $BITBUCKET_BRANCH
  branches:
    release/2.x:
      - step:
        name: Push dev to drupal.org
        script:
          - git remote add drupal DerH4NNES@git.drupal.org:project/degov.git
          - git config --global push.default matching
          - git config --global user.name "SaschaHannes"
          - git checkout 8.x-2.x -f
          - git merge release/2.x
          - git push drupal 8.x-2.x

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless