# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: derh4nnes/pipeline-behat:latest
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - apt-get install -y sqlite3 php7.1-sqlite
          - cd project
          - composer install
          - mkdir docroot/profiles
          - mkdir docroot/profiles/contrib
          - mkdir docroot/profiles/contrib/degov
          - find . -maxdepth 1 -type f -exec mv {} docroot/profiles/contrib/degov \;
          - mv docroot/profiles/contrib/degov/composer.* .
          - mv modules docroot/profiles/contrib/degov
          - mv testing docroot/profiles/contrib/degov
          - composer dump-autoload
          - php -S localhost:80 -t docroot &
          - bin/drush si degov

          # Execute tests
          - bin/behat --strict
        services:
          - testing

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
