# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: derh4nnes/pipeline-behat:feature_php-7.2
clone:
  depth: full
options:
  docker: true

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
          - docker
        script:
          - composer create-project degov/degov-project --no-install
          - cd degov-project
          - rm composer.lock
          - composer require degov/degov:dev-$BITBUCKET_BRANCH#$BITBUCKET_COMMIT
          - docker run -d --name="testing" -p 4444:4444 --net="host" -v $BITBUCKET_CLONE_DIR/degov-project/docroot/profiles/contrib/degov/testing/fixtures:/home/headless/ -v /dev/shm:/dev/shm -v $BITBUCKET_CLONE_DIR:$BITBUCKET_CLONE_DIR derh4nnes/selenium-chrome-headless
          - cp docroot/profiles/contrib/degov/testing/behat/composer-require-namespace.php .
          - php composer-require-namespace.php
          - composer dump-autoload
          - screen -dmS php-server php -S localhost:80 -t docroot &
          - export PATH="$HOME/.composer/vendor/bin:$PATH"
          - phpstan analyse docroot/profiles/contrib/degov -c docroot/profiles/contrib/degov/phpstan.neon --level=1 || true
          - (cd docroot/profiles/contrib/degov && phpunit --testdox)
          - cp docroot/profiles/contrib/degov/testing/behat/template/settings.local.php docroot/sites/default/settings.local.php
          - sed -i 's/{{ mysql_auth.db }}/testing/g' docroot/sites/default/settings.local.php
          - sed -i 's/{{ mysql_auth.user }}/root/g' docroot/sites/default/settings.local.php
          - sed -i 's/{{ mysql_auth.password }}/testing/g' docroot/sites/default/settings.local.php
          - sed -i 's/localhost/127.0.0.1/g' docroot/sites/default/settings.local.php
          - mv docroot/profiles/contrib/degov/testing/behat/behat-no-drupal.yml .
          - behat -c behat-no-drupal.yml -vvv
          - bin/drush locale-check && bin/drush locale-update && bin/drush cr
          - mv docroot/profiles/contrib/degov/testing/behat/behat.yml .
          - behat
        services:
          - docker
          - mysql
    - step:
        name: Deploy to platform.sh
        image: alpine/git
        script:
          - git config --global push.default matching
          - git remote add platform e5wm7rpj4nlbs@git.eu.platform.sh:e5wm7rpj4nlbs.git
          - git push platform $BITBUCKET_BRANCH
    - step:
        name: Push to drupal.org
        image: alpine/git
        script:
          - git remote add drupal DerH4NNES@git.drupal.org:project/degov.git
          - git config --global push.default matching
          - git config --global user.name "SaschaHannes"
          - git push drupal $BITBUCKET_BRANCH
  branches:
    release/2.x:
      - step:
          name: Build and test
          caches:
            - composer
          script:
            - composer create-project degov/degov-project --no-install
            - cd degov-project
            - rm composer.lock
            - composer require degov/degov:dev-$BITBUCKET_BRANCH#$BITBUCKET_COMMIT
            - docker run -d --name="testing" -p 4444:4444 --net="host" -v $BITBUCKET_CLONE_DIR/degov-project/docroot/profiles/contrib/degov/testing/fixtures:/home/headless/ -v /dev/shm:/dev/shm -v $BITBUCKET_CLONE_DIR:$BITBUCKET_CLONE_DIR derh4nnes/selenium-chrome-headless
            - cp docroot/profiles/contrib/degov/testing/behat/composer-require-namespace.php .
            - php composer-require-namespace.php
            - composer dump-autoload
            - screen -dmS php-server php -S localhost:80 -t docroot &
            - export PATH="$HOME/.composer/vendor/bin:$PATH"
            - phpstan analyse docroot/profiles/contrib/degov -c docroot/profiles/contrib/degov/phpstan.neon --level=1 || true
            - (cd docroot/profiles/contrib/degov && phpunit --testdox)
            - cp docroot/profiles/contrib/degov/testing/behat/template/settings.local.php docroot/sites/default/settings.local.php
            - sed -i 's/{{ mysql_auth.db }}/testing/g' docroot/sites/default/settings.local.php
            - sed -i 's/{{ mysql_auth.user }}/root/g' docroot/sites/default/settings.local.php
            - sed -i 's/{{ mysql_auth.password }}/testing/g' docroot/sites/default/settings.local.php
            - sed -i 's/localhost/127.0.0.1/g' docroot/sites/default/settings.local.php
            - mv docroot/profiles/contrib/degov/testing/behat/behat-no-drupal.yml .
            - behat -c behat-no-drupal.yml -vvv
            - bin/drush locale-check && bin/drush locale-update && bin/drush cr
            - mv docroot/profiles/contrib/degov/testing/behat/behat.yml .
            - behat
          services:
            - docker
            - mysql
      - step:
          name: Deploy to platform.sh
          image: alpine/git
          script:
            - git config --global push.default matching
            - git remote add platform e5wm7rpj4nlbs@git.eu.platform.sh:e5wm7rpj4nlbs.git
            - git push platform $BITBUCKET_BRANCH
      - step:
          name: Push dev to drupal.org
          image: alpine/git
          script:
            - git remote add drupal DerH4NNES@git.drupal.org:project/degov.git
            - git config --global push.default matching
            - git config --global user.name "SaschaHannes"
            - git fetch drupal
            - git checkout 8.x-2.x -f
            - git merge release/2.x
            - git push drupal 8.x-2.x
  tags:
    '*':
      - step:
          name: Pushing tags to drupal.org
          image: alpine/git
          script:
            - git remote add drupal DerH4NNES@git.drupal.org:project/degov.git
            - git config --global push.default matching
            - git config --global user.name "SaschaHannes"
            - git fetch drupal
            - git checkout drupal/8.x-2.x -f
            - git tag $(./scripts/transform.sh --tag=$BITBUCKET_TAG)
            - git push drupal $(./scripts/transform.sh --tag=$BITBUCKET_TAG)

definitions:
  services:
    mysql:
      image: mysql:5.7
      memory: 1024
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: testing
