image: derh4nnes/pipeline-behat:latest
clone:
  depth: full
options:
  docker: true
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Acceptance tests (new install - PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - scripts/pipeline_behat_new_install.sh
          services:
            - mysql
            - docker
      - step:
          name: Acceptance tests (from db-dump - PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - scripts/pipeline_behat_db_dump.sh
          services:
            - mysql
            - docker
      - step:
          name: Acceptance tests (new install - PHP 7.1)
          caches:
            - composer
            - docker
          script:
            - scripts/pipeline_behat_new_install.sh
          services:
            - mysql
            - docker
      - step:
          name: Acceptance tests (from db-dump - PHP 7.1)
          caches:
            - composer
            - docker
          script:
            - scripts/pipeline_behat_db_dump.sh
          services:
            - mysql
            - docker
      - step:
          name: Unit/functional tests and static code analysis (PHP 7.1)
          image: derh4nnes/pipeline-behat:latest
          script:
            - scripts/pipeline_code_tests.sh 7.1
      - step:
          name: Unit/functional tests and static code analysis (PHP 7.2)
          image: derh4nnes/pipeline-behat:latest
          script:
            - scripts/pipeline_code_tests.sh 7.2

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: testing
