# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:17.10
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y wget
          - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
          - tar xzfp phantomjs-2.1.1-linux-x86_64.tar.bz2
          - chmod +x phantomjs-2.1.1-linux-x86_64 && ./phantomjs-2.1.1-linux-x86_64 --webdriver=4444 &
          - apt-get install -y unzip git curl php php-cli php-gd php-curl php7.1-sqlite
          - apt-get install -y php-dom php-json php-common php-mbstring
          - wget https://phar.phpunit.de/phpunit-4.8.9.phar
          - chmod +x phpunit-4.8.9.phar
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - php /usr/local/bin/composer create-project degov/degov-project:dev-release/1.x degov-project
          - cd degov-project
          - rm composer.lock && rm -rf vendor/
          - composer require drupal/drupal-extension:^3.2 behat/mink:~1.7 behat/mink-goutte-driver:~1.2 behat/behat:^3.0
          - composer dump-autoload
          - export PATH="$HOME/.composer/vendor/bin:$PATH"
          - composer global require drush/drush:9.1.0
          - cd docroot
          - drush si degov --db-url=sqlite://sites/default/files/db.sqlite -y
          - php -S localhost:8000 &
          - cd ../../
          - php ./phpunit-4.8.9.phar
          - cd degov-project
          - rm -rf docroot/modules/contrib/lightning_layout/tests/contexts
          - rm -rf docroot/modules/contrib/lightning_media/tests/contexts
          - cp ../behat.yml .
          - bin/behat