image: derh4nnes/pipeline-behat:feature_php-7.2
clone:
  depth: full
options:
  docker: true
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Unit/functional tests and static code analysis
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/code_tests.sh
      - step:
          name: Content features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh content db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
      - step:
          name: Entities features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh entities db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
      - step:
          name: Access features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh access db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
      - step:
          name: View mode features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh view_mode db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
      - step:
          name: Form features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh form db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
      - step:
          name: Simplenews feature
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh simplenews db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
      - step:
          name: Social media sharing feature
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh social_media_sharing db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
      - step:
          name: Webforms feature
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh webforms db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
      - step:
          name: Smoke tests
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh smoke_tests db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
  branches:
    release/*:
      - parallel:
        - step:
            name: Unit/functional tests and static code analysis
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/code_tests.sh
            artifacts:
              - php_error.log
        - step:
            name: Content features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh content install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
        - step:
            name: Entities features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh entities install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
        - step:
            name: Access features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh access install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
        - step:
            name: View mode features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh view_mode install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
        - step:
            name: Form features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh form install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
        - step:
            name: Simplenews feature
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh simplenews install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
        - step:
            name: Social media sharing feature
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh social_media_sharing install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
        - step:
            name: Webforms feature
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh webforms install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
        - step:
            name: Smoke tests
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/behat.sh smoke_tests install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
