# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: derh4nnes/pipeline-behat:latest
clone:
  depth: 1

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - composer create-project degov/degov-project
          - cd degov-project
          - composer require degov/degov:dev-release/2.x#$BITBUCKET_COMMIT
          - php -S localhost:80 -t docroot &
          - export PATH="$HOME/.composer/vendor/bin:$PATH"
          - phpstan analyse docroot/profiles/contrib/degov -c docroot/profiles/contrib/degov/phpstan.neon --level=1 || true
          - (cd docroot/profiles/contrib/degov && phpunit)
          - bin/drush si degov --db-url=sqlite://sites/default/files/db.sqlite -y
          - mv docroot/profiles/contrib/degov/behat.yml .
          - behat
        services:
          - testing

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless