# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: derh4nnes/pipeline-behat:latest
clone:
  depth: full
options:
  docker: true
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Build and test (PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - scripts/pipeline.sh 7.2
          services:
            - docker
            - mysql
      - step:
          name: Build and test (PHP 7.1)
          image: derh4nnes/pipeline-behat:latest
          script:
            - scripts/pipeline.sh 7.1
          services:
            - docker
            - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      memory: 1024
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: testing
    mysql2:
      image: mysql:5.7
      memory: 1024
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: testing
