# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: debian:stretch
clone:
  depth: full
options:
  docker: true
  size: 2x

.install_docker_compose: &install_docker_compose |
  apt-get update
  apt-get install -y python-pip
  pip install docker-compose

.runner: &runner |
  docker-compose up -d testing mysql
  docker exec testing bash -c 'sudo mkdir -p /degov-project/docroot/profiles/contrib/degov && sudo chown -R headless:headless /degov-project'
  docker cp . testing:/degov-project/docroot/profiles/contrib/degov
  export COMPOSE_RESULT="$(docker-compose up --exit-code-from=app app)"
  docker logs app
  if [[ $(docker ps -a|grep "Exit(1)") -eq "" ]] ; then exit 0 ; else exit 1; fi

pipelines:
  default:
    - step:
        name: Build and test (PHP 7.2)
        script:
          - *install_docker_compose
          - *runner
        artifacts:
          - /app/dump.sql.gz
        services:
          - docker
    - step:
        name: Push to drupal.org
        image: alpine/git
        script:
          - git remote add drupal git@git.drupal.org:project/degov.git
          - git config --global push.default matching
          - git config --global user.name "SaschaHannes"
          - git push drupal $BITBUCKET_BRANCH
  branches:
    release/6.x:
      - step:
          name: Build and test (PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - *install_docker_compose
            - docker-compose up -d testing mysql
            - docker-compose up --exit-code-from=app app
          services:
            - docker
      - step:
          name: Push dev to drupal.org
          image: alpine/git
          script:
            - git remote add drupal git@git.drupal.org:project/degov.git
            - git config --global push.default matching
            - git config --global user.name "SaschaHannes"
            - git fetch drupal
            - git checkout 8.x-6.x -f
            - git merge release/6.x
            - git push drupal 8.x-6.x
  tags:
    '*':
      - step:
          name: Pushing tags to drupal.org
          image: alpine/git
          script:
            - git remote add drupal git@git.drupal.org:project/degov.git
            - git config --global push.default matching
            - git config --global user.name "SaschaHannes"
            - git fetch drupal
            - git checkout drupal/8.x-6.x -f
            - git tag $(./scripts/transform.sh --tag=$BITBUCKET_TAG)
            - git push drupal $(./scripts/transform.sh --tag=$BITBUCKET_TAG)

definitions:
  services:
    docker:
      memory: 6000
