image: derh4nnes/pipeline-behat:feature_php-7.2
clone:
  depth: full
options:
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Unit tests and analysis (PHP 7.2)
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_code_tests.sh
      - step:
          name: Behat new install (PHP 7.2)
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh
          artifacts:
            - ~/dump.sql.gz
          services:
            - mysql
            - testing

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: new_install