image: derh4nnes/pipeline-behat:feature_php-7.2
clone:
  depth: full
options:
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Unit/functional tests and static code analysis
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_code_tests.sh
      - step:
          name: Content features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh content
          services:
            - mysql
            - testing
      - step:
          name: Entities features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh entities
          services:
            - mysql
            - testing
      - step:
          name: Access features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh access
          services:
            - mysql
            - testing
      - step:
          name: View mode features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh view_mode
          services:
            - mysql
            - testing
      - step:
          name: Form features
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh form
          services:
            - mysql
            - testing
      - step:
          name: Simplenews feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh simplenews
          services:
            - mysql
            - testing
      - step:
          name: Social media sharing feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh social_media_sharing
          services:
            - mysql
            - testing
      - step:
          name: Webforms feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh webforms
          services:
            - mysql
            - testing
      - step:
          name: Smoke tests
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat_smoke_tests.sh
          services:
            - mysql
            - testing

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
    mysql:
      image: mysql:5.7
      memory: 1024
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: new_install