image: debian:stretch
clone:
  depth: full
options:
  docker: true
  size: 2x

.install_docker_compose: &install_docker_compose |
  apt-get update
  apt-get install -y python-pip
  pip install docker-compose

.unit_tests_analysis_runner: &unit_tests_analysis_runner |
  docker-compose up unit_tests_analysis

.behat_existing_install_runner: &behat_existing_install_runner |
  docker-compose up -d selenium-chrome-headless mysql
  docker exec selenium-chrome-headless bash -c 'sudo mkdir -p /degov-project/docroot/profiles/contrib/degov && sudo chown -R headless:headless /degov-project'
  docker cp . selenium-chrome-headless:/degov-project/docroot/profiles/contrib/degov
  export COMPOSE_RESULT="$(docker-compose up --exit-code-from=behat_existing_install behat_existing_install)"
  docker logs behat_existing_install
  if [[ $(docker ps -a|grep "Exit(1)") -eq "" ]] ; then exit 0 ; else exit 1; fi

.behat_new_install_runner: &behat_new_install_runner |
  docker-compose up -d selenium-chrome-headless mysql
  docker exec selenium-chrome-headless bash -c 'sudo mkdir -p /degov-project/docroot/profiles/contrib/degov && sudo chown -R headless:headless /degov-project'
  docker cp . selenium-chrome-headless:/degov-project/docroot/profiles/contrib/degov
  export COMPOSE_RESULT="$(docker-compose up --exit-code-from=behat_new_install behat_new_install)"
  docker logs behat_new_install
  if [[ $(docker ps -a|grep "Exit(1)") -eq "" ]] ; then exit 0 ; else exit 1; fi

pipelines:
  default:
    - parallel:
      - step:
          name: Unit tests and analysis (PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - *install_docker_compose
            - *unit_tests_analysis_runner
          artifacts:
            - /app/dump.sql.gz
          services:
            - docker
      - step:
          name: Behat existing install (PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - *install_docker_compose
            - *behat_existing_install_runner
          artifacts:
            - /app/dump.sql.gz
          services:
            - docker
      - step:
          name: Behat new install (PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - *install_docker_compose
            - *behat_existing_install_runner
          artifacts:
            - /app/dump.sql.gz
          services:
            - docker

definitions:
  services:
    docker:
      memory: 6000
