image: derh4nnes/pipeline-behat:feature_php-7.2
clone:
  depth: full
options:
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Unit/functional tests and static code analysis
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_code_tests.sh
      - step:
          name: content_creation.feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh content_creation
          artifacts:
            - ./*
          services:
            - mysql
            - testing
      - step:
          name: content_types.feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh content_types
          artifacts:
            - ./*
          services:
            - mysql
            - testing
      - step:
          name: demo_content.feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh demo_content
          artifacts:
            - ./*
          services:
            - mysql
            - testing
      - step:
          name: editorial.feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh editorial
          artifacts:
            - ./*
          services:
            - mysql
            - testing
      - step:
          name: file_management.feature
          caches:
            - composer
          script:
            - sh $BITBUCKET_CLONE_DIR/scripts/pipeline_behat.sh file_management
          artifacts:
            - ./*
          services:
            - mysql
            - testing

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
    mysql:
      image: mysql:5.7
      memory: 1024
      environment:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: new_install