image: derh4nnes/pipeline-behat:feature_php-7.2
clone:
  depth: full
options:
  docker: true
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Unit tests and analysis (PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - *install_docker_compose
            - *unit_tests_analysis_runner
          services:
            - docker
      - step:
          name: Behat existing install (PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - *install_docker_compose
            - *behat_existing_install_runner
          artifacts:
            - /app/dump.sql.gz
          services:
            - docker
      - step:
          name: Behat new install (PHP 7.2)
          caches:
            - composer
            - docker
          script:
            - *install_docker_compose
            - *behat_new_install_runner
          artifacts:
            - /app/dump.sql.gz
          services:
            - docker

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
    mysql:
      image: mysql:5.7
      variables:
        MYSQL_ROOT_PASSWORD: testing
        MYSQL_DATABASE: testing
