version: "2"
services:
  selenium-chrome-headless:
    container_name: "selenium-chrome-headless"
    image: "derh4nnes/selenium-chrome-headless"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
      BITBUCKET_CLONE_DIR: "$BITBUCKET_CLONE_DIR"
  behat_new_install:
    image: "derh4nnes/pipeline-behat:feature_php-7.2"
    container_name: "behat_new_install"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
      BITBUCKET_CLONE_DIR: "$BITBUCKET_CLONE_DIR"
    entrypoint: /bin/bash
    command: $BITBUCKET_CLONE_DIR/scripts/pipeline_behat_new_install.sh
    volumes:
      - "$BITBUCKET_CLONE_DIR:$BITBUCKET_CLONE_DIR"
  behat_existing_install:
    image: "derh4nnes/pipeline-behat:feature_php-7.2"
    container_name: "behat_existing_install"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
      BITBUCKET_CLONE_DIR: "$BITBUCKET_CLONE_DIR"
    entrypoint: /bin/bash
    command: $BITBUCKET_CLONE_DIR/scripts/pipeline_behat_db_dump.sh
    volumes:
      - "$BITBUCKET_CLONE_DIR:$BITBUCKET_CLONE_DIR"
  unit_tests_analysis:
    image: "derh4nnes/pipeline-behat:feature_php-7.2"
    container_name: "unit_tests_analysis"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
      BITBUCKET_CLONE_DIR: "$BITBUCKET_CLONE_DIR"
    entrypoint: /bin/bash
    command: $BITBUCKET_CLONE_DIR/scripts/pipeline_code_tests.sh
    volumes:
      - "$BITBUCKET_CLONE_DIR:$BITBUCKET_CLONE_DIR"
  mysql:
    image: mysql:5.7
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: testing
    command: " --max_allowed_packet=1024M"
