version: "2"
services:
  testing:
    container_name: "testing"
    image: "derh4nnes/selenium-chrome-headless"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
      BITBUCKET_PARALLEL_STEP: "$BITBUCKET_PARALLEL_STEP"
      BITBUCKET_CLONE_DIR: "$BITBUCKET_CLONE_DIR"
    volumes_from:
      - app:ro
    ports:
      - "4444:4444"
    networks:
      backend:
        ipv4_address: 172.16.31.3
  app:
    image: "derh4nnes/pipeline-behat:feature_php-7.2"
    container_name: "app"
    ports:
      - "80:80"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
      BITBUCKET_PARALLEL_STEP: "$BITBUCKET_PARALLEL_STEP"
      BITBUCKET_CLONE_DIR: "$BITBUCKET_CLONE_DIR"
    entrypoint: /bin/bash
    command: $BITBUCKET_CLONE_DIR/scripts/pipeline.sh
    volumes:
      - "$BITBUCKET_CLONE_DIR:$BITBUCKET_CLONE_DIR"
    networks:
      backend:
        ipv4_address: 172.16.31.2
  mysql:
    image: mechtecs/docker_big_mysql
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: testing
    ports:
      - "3306:3306"
    networks:
      backend:
        ipv4_address: 172.16.31.4
networks:
  backend:
    ipam:
      config:
      -
        subnet: 172.16.31.0/24