version: "2"
services:
  testing:
    container_name: "testing"
    image: "derh4nnes/selenium-chrome-headless"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
      BITBUCKET_PARALLEL_STEP: "$BITBUCKET_PARALLEL_STEP"
      BITBUCKET_CLONE_DIR: "$BITBUCKET_CLONE_DIR"
  app:
    image: "derh4nnes/pipeline-behat:feature_php-7.2"
    container_name: "app"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
      BITBUCKET_PARALLEL_STEP: "$BITBUCKET_PARALLEL_STEP"
      BITBUCKET_CLONE_DIR: "$BITBUCKET_CLONE_DIR"
    entrypoint: /bin/bash
    command: $BITBUCKET_CLONE_DIR/scripts/pipeline.sh
    volumes:
      - "$BITBUCKET_CLONE_DIR:$BITBUCKET_CLONE_DIR"
  mysql:
    image: mechtecs/docker_big_mysql
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: testing