dependencies:
  config:
    - image.style.teaser_squared_1_1_240
content:
  image:
    type: image
    weight: 0
    region: content
    label: hidden
    settings:
      image_style: teaser_squared_1_1_240
      image_link: ''
    third_party_settings: {  }