content:
  field_media_publish_date:
    weight: 11
    label: above
    settings:
      format_type: 'j. F Y'
      timezone_override: ''
    third_party_settings: {  }
    type: datetime_custom
    region: content
