dependencies:
  config:
    - field.field.media.image.field_royalty_free
third_party_settings:
  field_group:
    group_description:
      children:
        - field_image_date
        - field_image_caption
        - field_copyright
        - field_royalty_free
        - field_description
content:
  field_royalty_free:
    type: boolean_checkbox
    weight: 13
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
