dependencies:
  config:
    - field.field.media.image.field_royalty_free
content:
  field_copyright:
    type: entity_reference_label
    weight: 2
    region: content
    label: hidden
    settings:
      link: true
    third_party_settings: {  }
hidden:
  created: true
  field_allow_download: true
  field_description: true
  field_image_caption: true
  field_image_date: true
  field_image_height: true
  field_image_mime: true
  field_image_width: true
  field_include_search: true
  field_media_in_library: true
  field_royalty_free: true
  field_subtitle: true
  field_tags: true
  langcode: true
  name: true
  thumbnail: true
  uid: true
