dependencies:
  config:
    - field.field.media.image.field_royalty_free
hidden:
  created: true
  field_allow_download: true
  field_image_caption: true
  field_include_search: true
  field_media_in_library: true
  field_royalty_free: true
  field_subtitle: true
  image: true
  langcode: true
  name: true
  thumbnail: true
  uid: true
