type_settings:
  states:
    needs_review:
      published: false
      default_revision: false
      label: 'Needs review'
      weight: 6:
  transitions:
    create_new_draft:
        from:
          - needs_review
    needs_review:
      label: 'Needs review'
      from:
        - draft
      to: needs_review
      weight: 5
    publish:
      from:
        - needs_review
