config_rewrite: replace
langcode: de
status: true
dependencies:
  config:
    - field.field.paragraph.faq.field_faq_text
    - field.field.paragraph.faq.field_faq_title
    - paragraphs.paragraphs_type.faq
  enforced:
    module:
      - degov_paragraph_faq
  module:
    - text
id: paragraph.faq.default
targetEntityType: paragraph
bundle: faq
mode: default
content:
  field_faq_title:
    weight: 0
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
  field_faq_text:
    weight: 1
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
    type: text_textarea
    region: content
  field_govbot_question:
    weight: 2
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
  field_govbot_answer:
    weight: 3
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
    type: text_textarea
    region: content
hidden:
  created: true
  status: true
  uid: true
