dependencies:
  config:
    - field.field.paragraph.faq.field_govbot_answer
    - field.field.paragraph.faq.field_govbot_question
    - paragraphs.paragraphs_type.faq
    - field.field.paragraph.faq.field_govbot_id
hidden:
  field_govbot_answer: true
  field_govbot_question: true
  field_govbot_id: true
