field_settings:
  nested_faq_paragraphs:
    label: 'Nested FAQ paragraphs'
    property_path: nested_faq_paragraphs
    type: text
datasource_settings:
  'entity:node':
    bundles:
      selected:
        - faq
processor_settings:
  html_filter:
    all_fields: true
    fields:
      - nested_faq_paragraphs
  ignorecase:
    fields:
      - nested_faq_paragraphs
  stopwords:
    fields:
      - nested_faq_paragraphs
  tokenizer:
    fields:
      - nested_faq_paragraphs
