# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
#     - example:
#         requires:
#           - build
      - install_with_db_dump:
         requires:
           - build
      - test:
         requires:
           - install_with_db_dump
      - install_with_behat:
          requires:
            - build


################################################################################
# YAML aliases
#  are used to define Docker images and common steps.
#  https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)#simple-example
################################################################################

# Docker Images
docker_images:
  - &baseimage
    image: digitaldonkey/circleci-degov:0.0.20
    environment:
      RELEASE_BRANCH: release/7.6.x-dev
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_EXIT_ON_PATCH_FAILURE: 1
      CIRCLECI_CACHE_TAG: v1
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
      TAR_OPTIONS: --same-permissions

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
  - &dbimage
    image: circleci/mysql:5.7-ram
    command: mysqld --max_allowed_packet=65011712
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing

# Common steps
common_steps:
  -  &runStartApache
    run:
      name: Start Apache
      command: |
        if [ -L /etc/apache2/sites-enabled/000-default.conf ]; then
          sudo a2dissite --quiet 000-default
        fi
        if [ ! -L /etc/apache2/sites-enabled/project.conf ]; then
          sudo a2ensite --quiet project
        fi
        sudo apachectl -D FOREGROUND
      background: true

  -  &runStartMysql
    run:
      name: Waiting for MySQL to be ready
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
      # @see https://circleci.com/docs/2.0/postgres-config/#example-mysql-project
      command: |
        # For whatever stupid reson we cant do this in Dockerfile, but drush requires mysql.
        sudo apt install default-mysql-client --no-install-recommends
        for i in `seq 1 10`;
        do
          nc -z 127.0.0.1 3306 && echo Success && exit 0
          echo -n .
          sleep 1
        done
        echo Failed waiting for MySQL && exit 1
  - &runPrepareLocalSettings
    run:
      name: DB-Dump settings.local.php
      # TODO
      # I don't understand why we use settings.local.php. Shouldn't we test with production settings?
      # IMHO we should only create and use ONE SINGE settings.php if possible.
      command: |
        cp docroot/profiles/contrib/degov/testing/behat/template/settings.local.php docroot/sites/default/settings.local.php
        sed -i "s/{{ mysql_auth.db }}/$MYSQL_DATABASE/g" docroot/sites/default/settings.local.php
        sed -i "s/{{ mysql_auth.user }}/$MYSQL_USER/g" docroot/sites/default/settings.local.php
        sed -i "s/{{ mysql_auth.password }}/$MYSQL_PASSWORD/g" docroot/sites/default/settings.local.php
        sed -i 's/{{ mysql_host }}/127.0.0.1/g' docroot/sites/default/settings.local.php
        echo '$settings["hash_salt"] = "7asdiugasd8f623gjwgasgf7a8stfasjdfsdafasdfasdfasdf";' >> docroot/sites/default/settings.local.php


jobs:
  build:
    docker:
      - *baseimage
    steps:
      - checkout:
          path: /home/circleci/project/docroot/profiles/contrib/

      ### Prepare git uses the code from "- checkout" step WITHOUT cloning repository. would be:
      #      - run:
      #          name: Prepare Cloning
      #          command: |
      #            mkdir -p ~/.ssh
      #            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      #            bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
      #            " >> ~/.ssh/known_hosts
      #            (umask 077; touch ~/.ssh/id_rsa)
      #            chmod 0600 ~/.ssh/id_rsa
      #            (cat <<EOF > ~/.ssh/id_rsa
      #            $CHECKOUT_KEY
      #            EOF
      #            )
      #            # use git+ssh instead of https
      #            git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
      #            git config --global gc.auto 0 || true

      - run:
          name: Repository Environment Variables for project and LFS
          command: |
              mkdir -p /tmp/ci-cache
              if git ls-remote --exit-code --heads https://digitaldonkey@bitbucket.org/publicplan/degov_project.git "$CIRCLE_BRANCH";
              then
                echo 'export PROJECT_BRANCH="$CIRCLE_BRANCH"' >> $BASH_ENV
              else
                echo 'export PROJECT_BRANCH="$RELEASE_BRANCH"' >> $BASH_ENV
              fi
              if git ls-remote --exit-code --heads https://digitaldonkey@bitbucket.org/publicplan/degov_devel_git_lfs.git "$CIRCLE_BRANCH";
                then
                  echo 'export LFS_BRANCH="$CIRCLE_BRANCH"' >> $BASH_ENV
                else
                  echo 'export LFS_BRANCH="$RELEASE_BRANCH"' >> $BASH_ENV
                fi
                echo 'export PATH="/home/circleci/project/bin:$PATH"' >> $BASH_ENV
                source $BASH_ENV
                echo "PROJECT_BRANCH = $PROJECT_BRANCH"
                echo "LFS_BRANCH = $LFS_BRANCH"
                # Used for caching
                echo "$PROJECT_BRANCH, $LFS_BRANCH, $CIRCLECI_CACHE_TAG," > /tmp/ci-cache/project-setup
                echo "$CIRCLE_SHA1, $CIRCLE_BRANCH, $PROJECT_BRANCH, $LFS_BRANCH, $CIRCLECI_CACHE_TAG" > /tmp/ci-cache/composer
#                if [ ! -f /tmp/ci-cache/profile-setup-lock ]; then
#                  # Generate file with arbitrary content to have a file for cache checksum.
#                  head -c 64 </dev/urandom > /tmp/ci-cache/profile-setup-lock
#                fi

     #  Composer cache
      - restore_cache:
         keys:
           - composer-global-cache-{{ epoch }}
           - composer-global-cache-


      # PROJECT SETUP
      - restore_cache:
         keys:
          - project-dependencies-project-setup-{{ checksum "/tmp/ci-cache/project-setup" }}
          - project-dependencies-project-setup-

      - run:
          name: Set up Project
          command: | # if not in cache
            if [ ! -f ./composer.json ]; then
              rm -rf ./*  # removing default -checkout as we use composer, but we keep circleci known_hosts setup.
              composer create-project --remove-vcs "degov/degov-project:dev-$PROJECT_BRANCH" --no-install --ansi --no-progress .
            else
              echo "Restored from cache"
            fi

      - save_cache:
          key: project-dependencies-project-setup-{{ checksum "/tmp/ci-cache/project-setup" }}
          paths:
           - .
           - /tmp/ci-cache

      # INSTALL PROFILE

      # - run:
      #     name: TEST LOCK CACHING
      #     command: | # if not in cache
      #       if [ -f /tmp/ci-cache/profile-setup-lock ]; then
      #         composer update --lock --ansi --no-progress
      #         git diff --no-index composer.lock /tmp/ci-cache/profile-setup-lock
      #       fi

      - run:
          name: Composer require deGov
          command: | # if not in cache
            if [ ! -f /tmp/ci-cache/profile-setup-lock ]; then
              rm composer.lock
              composer require "degov/degov:dev-$CIRCLE_BRANCH#$CIRCLE_SHA1" degov/degov_devel_git_lfs:dev-$LFS_BRANCH --update-with-all-dependencies --ansi --no-progress
            fi
            # Prepare Git LFS checkout.
            (cd docroot/profiles/contrib/degov/testing/lfs_data/ && git lfs install)
            cp composer.lock /tmp/ci-cache/profile-setup-lock

      # TODO
      # composer update --lock ??
      # For propper caching we would require a solution invloving composer.lock from commit which is not committed.
      # We should ensure to have everything updated at build time. ??
      # Probably
      # - check the lock file and compare with /tmp/ci-cache/profile-setup-lock
      #   - if lock differs then update project and "project-setup-done", use cache somehow.
      # - run:
      #     name: Composer update composer.lock
      #     command: |
      #       composer update --lock --ansi --no-progress
      #       cat composer.lock
      #       cat md5sum composer.lock

      # TODO More clear settings in code.
      # settings are spread out to settings.php and settings.local.php. It's unclear for me why/what should be where.

      - run:
          name: Set up Drupal config & directories
          command: |
            if [ ! -d docroot/sites/default/files/private/ ]; then
              DIRS='docroot/sites/default/files docroot/sites/default/files/translations docroot/sites/default/files/private config/sync'
              mkdir -p $DIRS
              chmod a+w $DIRS
              ls -al docroot/sites/default/files/

              tee <<EOF > docroot/sites/default/settings.php
            <?php # Don't prepend spaces here!!

              \$settings["file_private_path"] = "sites/default/files/private";
              \$settings["file_public_path"] = "sites/default/files";
              \$config["system.file"]["path"]["temporary"] = "/tmp";
              \$settings["trusted_host_patterns"] = ["^127.0.0.1$","^localhost$","^host.docker.internal$"];
              \$config["locale.settings"]["translation"]["path"] = "sites/default/files/translations";
              \$config["swiftmailer.transport"]["transport"] = "spool";
              \$config["swiftmailer.transport"]["spool_directory"] = "/tmp/swiftmailer-spool";
              \$base_url = 'http://localhost';
              \$config_directories[CONFIG_SYNC_DIRECTORY] = '../config/sync';
              # Increase drush 9 memory limit
              if (PHP_SAPI === 'cli') { ini_set('memory_limit', '512M'); }
              if (file_exists(dirname(__FILE__) . '/settings.local.php')) { require dirname(__FILE__) . '/settings.local.php'; }
            EOF
              cat docroot/sites/default/settings.php
            fi

      - run:
          name: Drush Config
          command: |
            if [ -L bin/drush ]; then

              # Create drushrc.php
              tee <<EOF > docroot/sites/default/drushrc.php
            <?php # Don't prepend spaces.

              \$options['r'] = '/home/circleci/project/docroot';
              \$options['l'] = 'http://localhost';
            EOF

              # Replace bin/drush
              unlink bin/drush
              tee <<EOF > bin/drush
            #!/bin/bash
              /usr/local/bin/php /home/circleci/project/vendor/drush/drush/drush -c /home/circleci/project/docroot/sites/default/drushrc.php --root=/home/circleci/project/docroot/ -l default --uri=localhost --yes "\$@"

            EOF
              chmod 755 bin/drush
              echo 'export DRUPAL_DB_URL="mysql://$MYSQL_USER:$MYSQL_PASSWORD@127.0.0.1:3306/$MYSQL_DATABASE"' >> $BASH_ENV
            fi


#      - save_cache:
#          key: project-dependencies-composer-{{ checksum "/tmp/ci-cache/profile-setup-lock" }}-{{ checksum "/tmp/ci-cache/composer" }}-{{ checksum "docroot/profiles/contrib/degov/.circleci/config.yml" }}
#          paths:
#           - .
#           - /tmp/ci-cache

      - save_cache:
          key: composer-global-cache-{{ epoch }}
          paths:
           - ~/.composer/cache

      - *runStartApache

# We need to save a cache based on the lock file which we don't commit :/
#      - save_cache:
#          key: project-dependencies-apache-vhost-{{ checksum "docroot/profiles/contrib/degov/.circleci/vhost.conf" }}-{{ checksum "docroot/profiles/contrib/degov/.circleci/config.yml" }}
#          paths:
#            - .

      - run:
          name: Remove Git Repos
          command: |
            find . | grep \\.git$ | xargs rm -rf

      - persist_to_workspace:
          root: /
          paths:
            - home/circleci/.ssh
            - home/circleci/.drush
            - home/circleci/project
            - tmp/ci-cache/*
            - tmp/.bash_env-*

  example:
    docker:
     - *baseimage
     - *dbimage
    steps:
      - attach_workspace:
          at: /
      - *runStartApache

      - run:
          name: Verify Checkout
          command: |
            echo "###"
            echo "working_directory: $(pwd)"
            echo "###"
            ls -al /home/circleci
            cat docroot/sites/default/settings.php

  install_with_db_dump:
    docker:
     - <<: *baseimage
     - <<: *dbimage
    steps:
      - attach_workspace:
          at: /
      - *runStartApache
      - *runStartMysql
      - *runPrepareLocalSettings
      - run:
          name: Install DB dump
          command: |
            cd docroot/
            drush status
            echo "DRUPAL_DB_URL: $DRUPAL_DB_URL"
            drush sql:drop --db-url="$DRUPAL_DB_URL"
            gunzip -c profiles/contrib/degov/testing/lfs_data/degov-7.x-dev.sql.gz | drush sqlc --db-url="$DRUPAL_DB_URL"
            drush cr
            drush watchdog:delete all
            drush updb
            drush cr
            drush pm:uninstall degov_demo_content
            drush pm:enable degov_demo_content
            drush locale:check
            drush locale:update
            drush php-eval 'Drupal\degov\TranslationImporter::importForProfile()'
            drush cr

  install_with_behat:
    docker:
     - *baseimage
     - *dbimage
     - image: selenium/standalone-chrome:3
    steps:
      - attach_workspace:
          at: /
      - *runStartApache
      - *runStartMysql
      - run:
          name: PHP life error log
          command: |
            tail -f /tmp/test-reports/php_error.log
          background: true

      - run:
          name: Install Drupal using Behat
          no_output_timeout: "20m"
          command: |
            chmod 666 docroot/sites/default/settings.php
            mv docroot/profiles/contrib/degov/testing/behat/behat-no-drupal.dist.yml .
            mv docroot/profiles/contrib/degov/testing/behat/behat.dist.yml .
            mkdir -p /tmp/test-reports/behat/install
            bin/behat --format=pretty --out=std --format=junit --out=/tmp/test-reports/behat/install -c behat-no-drupal.dist.yml --strict --colors
      - store_artifacts:
          path: /tmp/test-reports/php_error.log
      - store_test_results:
          path: /tmp/test-reports/behat/install

test:
    docker:
     - *baseimage
     - *dbimage
    steps:
      - attach_workspace:
          at: /
      - *runStartApache

      - run:
          name: Verify Checkout
          command: |
            echo "###"
            echo "working_directory: $(pwd)"
            echo "###"
            ls -al /home/circleci
            cat docroot/sites/default/settings.php

################################################################################
# SSH
# To use SSH you can click on a jobs contextual menu in UI and select "rerun with SSH".
################################################################################
#
# source $BASH_ENV
# sudo apt update && sudo apt install vim mysql-client nmap lynx
# nmap localhost -Pn 3306
# mysql -u testing -p -h 127.0.0.1 -P 3306 testing
# alias drush='/usr/local/bin/php /home/circleci/project/vendor/drush/drush/drush -c /home/circleci/project/docroot/sites/default/drushrc.php --root=/home/circleci/project/docroot/ -l default --uri=localhost --yes'
# circleci@defc4957b553:~/project$ test  php-eval 'print(ini_get("memory_limit")."\n");'
# gunzip -c project/docroot/profiles/contrib/degov/testing/lfs_data/degov-7.x-dev.sql.gz | drush sqlc --db-url="mysql://testing:testing@localhost:3306/testing"
# sudo chown -R circleci:www-data . && chmod -R g+w .

################################################################################
# Dockerfile building.
#
# cd docroot/profiles/contrib/degov/.circleci/images
# docker build -t digitaldonkey/circleci-degov:0.0.20 .
# docker push digitaldonkey/circleci-degov:0.0.20
################################################################################
