# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:apache-stretch
        environment:
          RELEASE_BRANCH: release/7.6.x-dev
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSER_MEMORY_LIMIT: -1
          COMPOSER_EXIT_ON_PATCH_FAILURE: 1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_DATABASE: testing
          MYSQL_USER: testing
          MYSQL_PASSWORD: testing

    steps:
      - checkout
      - run: sudo apt update && sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
      - run: sudo docker-php-ext-configure gd --with-freetype --with-jpeg && sudo docker-php-ext-install -j$(nproc) gd
      - run: sudo docker-php-ext-install zip

      - run:
          name: Check for PROJECT_BRANCH
          command: |
            if git ls-remote --exit-code --heads https://digitaldonkey@bitbucket.org/publicplan/degov_project.git "$CIRCLE_BRANCH";
            then
              echo 'export PROJECT_BRANCH="$CIRCLE_BRANCH"' >> $BASH_ENV
              echo "PROJECT_BRANCH = $CIRCLE_BRANCH"
            else
              echo 'export PROJECT_BRANCH="$RELEASE_BRANCH"' >> $BASH_ENV
              echo "PROJECT_BRANCH = $RELEASE_BRANCH"
            fi

      - run:
          name: Check for LFS_BRANCH
          command: |
            if git ls-remote --exit-code --heads https://digitaldonkey@bitbucket.org/publicplan/degov_devel_git_lfs.git "$CIRCLE_BRANCH";
            then
              echo 'export LFS_BRANCH="$CIRCLE_BRANCH"' >> $BASH_ENV
              echo "LFS_BRANCH = $CIRCLE_BRANCH"
            else
              echo 'export LFS_BRANCH="$RELEASE_BRANCH"' >> $BASH_ENV
              echo "LFS_BRANCH = $RELEASE_BRANCH"
            fi

      - run:
          name: Test  Environment Variables
          command: |
            echo "LFS BRANCH: $LFS_BRANCH"
            echo "PROJECT BRANCH: $PROJECT_BRANCH"


      # PROJECT SETUP
      - restore_cache:
          keys:
            - v1-project-dependencies-{{ .Environment.PROJECT_BRANCH }}-{{ .Environment.CIRCLE_BRANCH }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Set up Project
          command: |
            composer create-project --remove-vcs --no-progress "degov/degov-project:dev-$PROJECT_BRANCH" --no-install

      - save_cache:
          keys:
            - v1-project-dependencies-{{ .Environment.PROJECT_BRANCH }}-{{ .Environment.CIRCLE_BRANCH }}
          paths:
            - ./degov-project


      # INSTALL PROFILE
      - run:
          name: Install profile
          command: |
            cd degov-project
            rm composer.lock
            composer require --no-progress "degov/degov:dev-$CIRCLE_BRANCH#$CIRCLE_SHA1" degov/degov_devel_git_lfs:dev-$LFS_BRANCH --update-with-all-dependencies
            cd ..


#      - restore_cache:
#          keys:
#            - node-v1-{{ checksum "package.json" }}
#            - node-v1-
##      - run: yarn install
#      - save_cache:
#          key: node-v1-{{ checksum "package.json" }}
#          paths:
#            - node_modules

      # prepare the database
#      - run: touch storage/testing.sqlite
#      - run: php artisan migrate --env=testing --database=sqlite_testing --force

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
#      - run: ./vendor/bin/codecept build
#      - run: ./vendor/bin/codecept run
dependencies:
  cache_directories:
    - ~/.composer/cache
