content:
  scheduled_updates:
    type: inline_entity_form_complex
    weight: 11
    settings:
      form_mode: default
      override_labels: true
      label_singular: 'Scheduled Updates'
      label_plural: 'Scheduled Updatess'
      allow_new: true
      allow_existing: false
      match_operator: CONTAINS
    third_party_settings: {  }
    region: content
