dependencies:
  config:
    - field.field.media.audio.field_media_language
content:
  field_media_language:
    weight: 8
    label: above
    settings:
      link: false
    third_party_settings: {  }
    type: entity_reference_label
    region: content
