dependencies:
  config:
    - field.field.node.blog.field_section
content:
  field_section:
    type: options_select
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
