dependencies:
  config:
    - field.field.paragraph.media_reference.field_media_reference_view_mode
  module:
    - options
content:
  field_media_reference_view_mode:
    weight: 5
    label: above
    settings: {  }
    third_party_settings: {  }
    type: list_default
    region: content