dependencies:
  config:
    - field.field.paragraph.media_reference.field_media_reference_view_mode
content:
  field_media_reference_view_mode:
    weight: 6
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content