field_settings:
  field_media_publish_date:
    label: Veröffentlichungsdatum
    datasource_id: 'entity:media'
    property_path: field_media_publish_date
    type: date
    dependencies:
      config:
        - field.storage.media.field_media_publish_date
