dependencies:
  config:
    - field.field.media.audio.field_media_accessibility
content:
  field_media_accessibility:
    weight: 7
    label: above
    settings:
      link: false
    third_party_settings: {  }
    type: entity_reference_label
    region: content
