display:
  default:
    display_options:
      pager:
        options:
          items_per_page: 9
      style:
        options:
          row_class: 'no-padding'
      row:
        type: 'views_parity_row_entity:media'
        options:
          relationship: none
          view_mode: preview_wide
          views_parity_row_enable: 1
          views_parity_row:
            frequency: '3'
            start: '2'
            end: '0'
            view_mode: preview
      css_class: mediathek-slides
